# Site settings
title:          Jai Notes
description:    "my programming notes"
url:            "https://notes.jaironlanda.com/"

# Google Analytics
google_analytics: #UA—XXXXXXXX-X

# Author
author:
  name:         Jairon Landa
  url:          https://jaironlanda.com
  email:        jaironlanda@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         #jekyll-tale